steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/vertexai-explore-437408/filter-smart-service', '-f', 'agents/filter_smart/Dockerfile', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/vertexai-explore-437408/filter-smart-service']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'filter-smart-service'
  - '--image'
  - 'gcr.io/vertexai-explore-437408/filter-smart-service'
  - '--region'
  - 'europe-west9'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
