steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/vertexai-explore-437408/engage-service', '-f', 'agents/engage/Dockerfile', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/vertexai-explore-437408/engage-service']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'engage-service'
  - '--image'
  - 'gcr.io/vertexai-explore-437408/engage-service'
  - '--region'
  - 'europe-west9'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--cpu'
  - '2'
  - '--memory'
  - '2Gi'
  - '--min-instances'
  - '1'
  - '--no-cpu-throttling'
